### ISSUE TITLE
Issues when running commands - Application is not authorized to perform this operation. 

### ISSUE THREAD

**Issue by bwya77** [srozemuller/IntuneAssistant#6]
I have successfully signed into the IntuneAssistant but when I run something like 
`./IntuneAssistant.Cli show assignments groups`

I get the following error 
```
    ⣟ Fetching group assignments overview from Intune
                                                 An exception has occurred while fetching compliance policies: Microsoft.Graph.Beta.Models.ODataErrors.ODataError: {
  "_version": 3,
  "Message": "Application is not authorized to perform this operation. Application must have one of the following scopes: DeviceManagementConfiguration.Read.All, DeviceManagementConfiguration.ReadWrite.All - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 8191cc94-6c68-4ae6-a843-dcb7f44d2765 - Url: https://fef.amsua0202.manage.microsoft.com/DeviceConfiguration_2311/StatelessDeviceConfigurationFEService/deviceManagement/deviceCompliancePolicies?api-version=5023-10-14&$expand=assignments",
  "CustomApiErrorPhrase": "",
  "RetryAfter": null,
  "ErrorSourceService": "",
  "HttpHeaders": "{}"
}
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
                                                 eCompliancePolicies.DeviceCompliancePoliciesRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)
⢿ Fetching group assignments overview from Intune
                                                 An exception has occurred while fetching configuration policies: Microsoft.Graph.Beta.Models.ODataErrors.ODataError: {
  "_version": 3,
  "Message": "Application is not authorized to perform this operation. Application must have one of the following scopes: DeviceManagementConfiguration.Read.All, DeviceManagementConfiguration.ReadWrite.All - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: ba699639-6393-4fdd-97be-ec66ae0d115c - Url: https://fef.amsua0202.manage.microsoft.com/DeviceConfigV2/DCV2GraphService/de147310-ffff-8549-1134-112219025354/deviceManagement/configurationPolicies?api-version=5023-08-14&$select=createdDateTime%2ccreationSource%2cdescription%2clastModifiedDateTime%2cname%2cplatforms%2cpriorityMetaData%2croleScopeTagIds%2csettingCount%2ctechnologies%2ctemplateReference%2cid&$expand=assignments",
  "CustomApiErrorPhrase": "",
  "RetryAfter": null,
  "ErrorSourceService": "",
  "HttpHeaders": "{}"
}
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
                                                 gurationPolicies.ConfigurationPoliciesRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)
⣽ Fetching group assignments overview from Intune
                                                 An exception has occurred while fetching script assignments: Microsoft.Graph.Beta.Models.ODataErrors.ODataError: {
  "_version": 3,
  "Message": "Application is not authorized to perform this operation. Application must have one of the following scopes: DeviceManagementConfiguration.Read.All, DeviceManagementConfiguration.ReadWrite.All - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 66811d8a-f8c3-4c29-adab-7749bb7d34e0 - Url: https://fef.amsua0202.manage.microsoft.com/DeviceFE/StatelessDeviceFEService/deviceManagement/deviceManagementScripts?api-version=5023-09-09&$expand=assignments",
  "CustomApiErrorPhrase": "",
  "RetryAfter": null,
  "ErrorSourceService": "",
  "HttpHeaders": "{}"
}
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
                                                 eManagementScripts.DeviceManagementScriptsRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)
⣷ Fetching group assignments overview from Intune
                                                 An exception has occurred while fetching autopilot policies: Microsoft.Graph.Beta.Models.ODataErrors.ODataError: Application is not authorized to perform this operation. Application must have one of the following scopes: DeviceManagementConfiguration.Read.All, DeviceManagementConfiguration.ReadWrite.All
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
                                                 eHealthScripts.DeviceHealthScriptsRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)
⣟ Fetching group assignments overview from Intune
                                                 An exception has occurred while fetching autopilot policies: Microsoft.Graph.Beta.Models.ODataErrors.ODataError: {
  "_version": 3,
  "Message": "Application is not authorized to perform this operation. Application must have one of the following scopes: DeviceManagementServiceConfiguration.Read.All, DeviceManagementServiceConfig.Read.All, DeviceManagementServiceConfiguration.ReadWrite.All, DeviceManagementServiceConfig.ReadWrite.All - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 9f359a68-e433-4d9d-b66c-280176195494 - Url: https://fef.amsua0202.manage.microsoft.com/DeviceEnrollmentFE/StatelessDeviceEnrollmentFEService/deviceManagement/windowsAutopilotDeploymentProfiles?api-version=5023-06-28&$expand=assignments",
  "CustomApiErrorPhrase": "",
  "RetryAfter": null,
  "ErrorSourceService": "",
  "HttpHeaders": "{}"
}
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
                                                 wsAutopilotDeploymentProfiles.WindowsAutopilotDeploymentProfilesRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)
⣻ Fetching group assignments overview from Intune
                                                 An exception has occurred while fetching autopilot policies: Microsoft.Graph.Beta.Models.ODataErrors.ODataError: {
  "_version": 3,
  "Message": "Application is not authorized to perform this operation. Application must have one of the following scopes: DeviceManagementApps.Read.All, DeviceManagementApps.ReadWrite.All - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: baaf11ad-1654-4807-b2ec-07dae73de02d - Url: https://fef.amsua0202.manage.microsoft.com/MAMAdmin_2311/MAMAdminFEService/deviceAppManagement/windowsManagedAppProtections?api-version=5023-09-19&$expand=assignments",
  "CustomApiErrorPhrase": "",
  "RetryAfter": null,
  "ErrorSourceService": "",
  "HttpHeaders": "{}"
}
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
                                                 ndowsManagedAppProtections.WindowsManagedAppProtectionsRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)
⣾ Fetching group assignments overview from Intune
                                                 An exception has occurred while fetching mobile app assignments: Microsoft.Graph.Beta.Models.ODataErrors.ODataError: {
  "_version": 3,
  "Message": "Application is not authorized to perform this operation. Application must have one of the following scopes: DeviceManagementApps.Read.All, DeviceManagementApps.ReadWrite.All - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: b383c8d5-aab1-4abe-94de-60cf726b0041 - Url: https://fef.amsua0202.manage.microsoft.com/AppLifecycle_2311/StatelessAppMetadataFEService/deviceAppManagement/mobileApps?api-version=5023-09-11&$expand=assignments",
  "CustomApiErrorPhrase": "",
  "RetryAfter": null,
  "ErrorSourceService": "",
  "HttpHeaders": "{}"
}
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
                                                 bileApps.MobileAppsRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)
⣷ Fetching group assignments overview from Intune
                                                 An exception has occurred while fetching autopilot policies: Microsoft.Graph.Beta.Models.ODataErrors.ODataError: {
  "_version": 3,
  "Message": "Application is not authorized to perform this operation. Application must have one of the following scopes: DeviceManagementApps.Read.All, DeviceManagementApps.ReadWrite.All - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 22a9d448-e273-4a1d-b06f-c9e005fc6fe9 - Url: https://fef.amsua0202.manage.microsoft.com/MAMAdmin_2311/MAMAdminFEService/deviceAppManagement/targetedManagedAppConfigurations?api-version=5023-09-19&$expand=assignments",
  "CustomApiErrorPhrase": "",
  "RetryAfter": null,
  "ErrorSourceService": "",
  "HttpHeaders": "{}"
}
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
No assignments found in Intune.
```

I authenticated with a Global Admin, I have licenses for Intune and confirmed I have group assignments. 

Running this on MacOS, M1 Pro
MacOS Sanoma Version 14.1.1 (23B81)

**Comment by srozemuller** [comment]
Can you try to authenticate using a private browser session.  It seems you are using cached credentials and not consenting the common Graph application during interactive login.

**Comment by bwya77** [comment]
I have tried using a browser session after using the` ./IntuneAssistant.Cli auth logout` command and same error

**Comment by srozemuller** [comment]
Are you using PIM? If so, is the role activated? Did you also try an other account?

**Comment by bwya77** [comment]
That works! Thank you

**Comment by srozemuller** [comment]
Great to hear.  Will close the issue.
